$(eval 
  words = ['arc', 'minato aqua', 'cat', 'dog', 'calibrate', 'extreme', 'easy', 'hard', 'insane', 'demon', 'normal', 'kyouki', 'haunted ship', 'robtop', 'die', 'love', 'kill', 'yourself', 'rngdle', 'fuck', 'bitch', 'moron', 'idiot', 'stupid', 'dumb', 'turnip', 'dzends', 'term', 'sc66p', 'drongostache', 'bilete', 'kaden', 'pohgii', 'spaceman', 'juic3y', 'poros', 'kermit', 'tokoyami towa', 'command', 'help', 'ship', 'wave', 'cube', 'spider', 'ball', 'swing', 'ufo', 'penis', 'jerk', 'masturbate', 'vagina', 'pussy', 'eater', 'collab', 'level', 'hardest', 'geometry', 'dash', 'jump', 'click', 'cbf', 'frame perfect', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'grief', 'heliopolis', 'tidal wave', 'vehemence', 'angelicide', 'aeternus', 'thinking space ii', 'ts2', 'amethyst', 'flamewall', 'i', 'can', 'cant', 'want', 'how', 'what', 'when', 'where', 'live', 'stream', 'twitch', 'youtube', 'steam', 'furry', 'vtuber', 'hololive', 'goon', 'gooning', 'song', 'music', 'name', 'computer', 'wooting', 'keyboard', 'monitor', '60 hz', '144 hz', '240 hz', '360 hz', 'frame', 'pixel', 'perfect', 'editor', 'doggie', 'zoink', 'wpopoff', 'trick', 'pedophile', 'groomer', 'diddy', 'israeli', 'shot', 'my', 'us', 'me', 'our', 'larp', 'ai', 'drop', 'rate', 'epic', 'feature', 'legendary', 'mythic', 'icons', 'robtop', 'viprin', 'pauze', 'suck', 'dick', 'lmao', 'lol', 'gg', 'ez', 'fucking', 'frick', 'freaking', 'freak', 'fricking', 'testicles', 'W', 'L', 'go', 'GO', 'predict', 'attempt', 'you', 'all', 'chat', 'follow', 'sub', 'subscribe', 'gift', 'gifted', 'to', 'from', 'a', 'by', 'before', 'after', 'then', 'than', 'whore', 'instead', 'or', 'either', 'rather', 'the', 'sorry', 'run', 'portal', 'orb', 'red', 'yellow', 'orange', 'green', 'cyan', 'blue', 'pink', 'purple', 'black', 'shit', 'poop', 'pee', 'piss', 'sleep', 'shower', 'wash', 'walk', 'word', 'really', 'wanna', 'gonna', 'get', 'gotta', 'light', 'is', 'it', 'gd', 'list', 'pointercrate', 'aredl', 'global list', 'mic', 'muted', 'holy', 'god', 'jesus', 'free', 'hitler']; 
  count = Math.floor(Math.random() * 8) + 1; 
  result = []; 
  for(i = 0; i < count; i++) { 
    result.push(words[Math.floor(Math.random() * words.length)]); 
  } 
  result.join(' ');
)
